FROM python:latest   
WORKDIR "/"
COPY ./ /
RUN pip3 install -r /req.txt
CMD ["python3", "/subscriber.py"]


#imagine de baza, bazata pe debian, cu python instalatt
#selectam root
#copiem cee local in root
# instalam ce e in requirements cu pipinstl
#comanda de exec